import { useEffect, useState } from "react";
import PageHeading from "../components/PageHeading.jsx";
import { CheckIcon } from "../components/Icons.jsx";

// Demo-only comparison page. Everything shown is generated by `make baseline`
// from TORGO corpus recordings (web/public/baseline/, gitignored); nothing is
// computed or simulated in the browser.
const RESULTS_URL = "/baseline/results.json";

const pct = (x) => `${(x * 100).toFixed(1)}%`;
const GROUP_LABEL = { dysarthric: "Speakers with dysarthria", control: "Control speakers" };

function Verdict({ accepted }) {
  return accepted
    ? <strong className="message-ok"><CheckIcon /> Accepted</strong>
    : <strong className="message-error"><span aria-hidden="true">✕ </span>Rejected</strong>;
}

export default function Baseline() {
  const [state, setState] = useState({ status: "loading" });

  useEffect(() => {
    let cancelled = false;
    fetch(RESULTS_URL)
      .then((res) => {
        if (!res.ok) throw new Error(`HTTP ${res.status}`);
        return res.json();
      })
      .then(
        (data) => !cancelled && setState({ status: "ready", data }),
        (err) => {
          console.error("baseline results failed to load", err);
          if (!cancelled) setState({ status: "error" });
        },
      );
    return () => { cancelled = true; };
  }, []);

  if (state.status === "loading") return <p aria-busy="true">Loading the comparison…</p>;
  if (state.status === "error") {
    return (
      <div className="stack">
        <PageHeading>Baseline comparison</PageHeading>
        <p className="message-error" role="alert">
          No baseline results on this machine yet. Run <code>make eval</code>, then <code>make baseline</code>, and reload.
        </p>
      </div>
    );
  }

  const { data } = state;
  const groups = ["dysarthric", "control"];
  return (
    <div className="stack baseline">
      <PageHeading>Two ways to check a voice</PageHeading>
      <p>
        Voice-gated systems today check <em>what you said</em>: they transcribe your answer and compare the
        words. Timbre checks <em>who is speaking</em>, from the sound of the voice. Below, both checks run on the
        same recordings from the TORGO corpus.
      </p>

      <section className="panel stack" aria-labelledby="baseline-rates">
        <h2 id="baseline-rates">How often each check says yes</h2>
        <div className="table-scroll">
          <table className="summary baseline-table">
            <caption className="visually-hidden">Acceptance rates for the transcription check and Timbre</caption>
            <thead>
              <tr>
                <th scope="col">Who is speaking</th>
                <th scope="col">Transcription check accepts the right person</th>
                <th scope="col">Timbre accepts the right person</th>
                <th scope="col">Transcription check accepts someone else</th>
                <th scope="col">Timbre accepts someone else</th>
              </tr>
            </thead>
            <tbody>
              {groups.map((g) => {
                const r = data.rates[g];
                return (
                  <tr key={g}>
                    <th scope="row">
                      {GROUP_LABEL[g]}
                      <br /><span className="note">{r.speakers} speakers, {r.genuine_trials} takes</span>
                    </th>
                    <td className="amount">{pct(r.baseline_accepts_genuine)}</td>
                    <td className="amount">{pct(r.timbre_accepts_genuine)}</td>
                    <td className="amount">{pct(r.baseline_accepts_impostor)}</td>
                    <td className="amount">{pct(r.timbre_accepts_impostor)}</td>
                  </tr>
                );
              })}
            </tbody>
          </table>
        </div>
        <p className="note">
          "Someone else" means another speaker's take checked against this person's account. The transcription check
          ignores who is speaking, so anyone who says the words clearly gets through. It passes a take when its
          word error rate against the prompt (substituted, missing, and extra words, over the prompt's length) is at
          most {pct(data.max_wer)}.
        </p>
      </section>

      <section className="stack" aria-labelledby="baseline-examples">
        <h2 id="baseline-examples">Listen: the same take, both checks</h2>
        <p className="note">{data.selection_rule}</p>
        {data.examples.length === 0 && <p>No take in this run was rejected by transcription and accepted by Timbre.</p>}
        <ul className="baseline-examples">
          {data.examples.map((ex) => (
            <li key={ex.audio} className="panel stack">
              <h3>Speaker {ex.speaker}, prompt “{ex.prompt}”</h3>
              <audio controls preload="none" src={`/baseline/${ex.audio}`} aria-label={`Recording of speaker ${ex.speaker} saying ${ex.prompt}`} />
              <div className="baseline-verdicts">
                <div className="stack">
                  <h4>Transcription check</h4>
                  <p>Heard: <span className="mono">{ex.heard ? `“${ex.heard}”` : "(nothing)"}</span></p>
                  <p>Word error rate {pct(ex.wer)} (passing needs {pct(data.max_wer)} or less)</p>
                  <Verdict accepted={false} />
                </div>
                <div className="stack">
                  <h4>Timbre</h4>
                  <p>Voice match score {ex.score.toFixed(2)}</p>
                  <p>Personal threshold {ex.threshold.toFixed(2)}</p>
                  <Verdict accepted />
                </div>
              </div>
            </li>
          ))}
        </ul>
      </section>

      <details className="panel">
        <summary>Per speaker</summary>
        <table className="summary">
          <caption className="visually-hidden">Acceptance of each speaker's own takes</caption>
          <thead>
            <tr><th scope="col">Speaker</th><th scope="col">Group</th><th scope="col">Takes</th>
              <th scope="col">Transcription accepts</th><th scope="col">Timbre accepts</th></tr>
          </thead>
          <tbody>
            {data.per_speaker.map((s) => (
              <tr key={s.speaker}>
                <th scope="row">{s.speaker}</th><td>{s.group}</td><td>{s.trials}</td>
                <td>{pct(s.baseline_accepts)}</td><td>{pct(s.timbre_accepts)}</td>
              </tr>
            ))}
          </tbody>
        </table>
      </details>

      <section className="stack" aria-labelledby="baseline-caveats">
        <h2 id="baseline-caveats">What this does and does not show</h2>
        <ul>
          <li>These are preliminary numbers from a small corpus, not a benchmark. Recordings are real corpus audio; no disabled speech is imitated.</li>
          <li>Timbre's template here is five different corpus words. Live enrollment uses five takes of one sound the person chooses, plus a passkey fallback. These rates do not model either.</li>
          <li>Speaker verification on dysarthric speech is an existing research area. This page shows why a transcription gate is the wrong test, not a new algorithm.</li>
          <li>Takes with no plain-word prompt were left out ({data.skipped_unscoreable_takes}). Generated {data.generated} by <code>make baseline</code>.</li>
        </ul>
      </section>
    </div>
  );
}
